### ISSUE TITLE
remove claim does not work

### ISSUE THREAD

**Issue by abajorunas** [codekoenig/AspNetCore.Identity.DocumentDb#12]
hi, 

the code below does not remove my claim from Cosmo db user object.

`await _userManager.RemoveClaimAsync(user, new Claim(ClaimTypes.Role, role));`

is there a bug or I am doing something wrong

**Comment by codekoenig** [comment]
Hi abajorunas,

sorry for the late reply. I will have a look if the relevant code works as expected and report back.

**Comment by abajorunas** [comment]
hey, did you had a chance to look at this?

**Comment by codekoenig** [comment]
Sorry again @abajorunas for the late reply ... I had very little spare time this month. However, I looked into it and the issue is that you are passing a `new` instance of `Claim`. A reference comparison is done, so you should get the `Claim` instance you want to remove from the user's claims list and pass that to the remove method.

So just pass the reference instead of creating a new instance with new values. I will have a look at the reference implementation to see if they might use value comparison here, ~~but I doubt that as it won't be good practice when expecting a reference as a parameter.~~ **Edit:** Actually, I looked at the reference implementation and they **do** a value comparison here, so I should follow accordingly. Thinking about it I also agree it makes sense for Claims.

So, I will fix this, but in the meantime you can pass the original claim reference to fix your issue.
